#!/bin/bash
# Crucible Hook: Session Compaction
# 세션 종료 시 현재 상태를 session-log에 기록합니다.
# 다음 세션에서 컨텍스트를 복구하는 데 사용됩니다.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
SESSION_LOG_DIR="$PROJECT_DIR/.claude/memory/session-log"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)
LOG_FILE="$SESSION_LOG_DIR/${DATE}-${TIME}-summary.md"

render_dir_list() {
    local target_dir="$1"
    if [ -d "$target_dir" ] && [ -n "$(ls -A "$target_dir" 2>/dev/null)" ]; then
        ls -1 "$target_dir" 2>/dev/null | head -10 | sed 's/^/- /'
    else
        echo "- None"
    fi
}

# session-log 디렉토리 확인
mkdir -p "$SESSION_LOG_DIR"

# 현재 Phase 확인
CURRENT_PHASE=""
SETTINGS_FILE="$PROJECT_DIR/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ] && command -v jq &>/dev/null; then
    CURRENT_PHASE=$(jq -r '.env.CRUCIBLE_PHASE // "unknown"' "$SETTINGS_FILE" 2>/dev/null || echo "unknown")
fi

# Git 상태 수집 (git repo인 경우만)
GIT_STATUS=""
GIT_RECENT=""
if [ -d "$PROJECT_DIR/.git" ]; then
    GIT_STATUS=$(cd "$PROJECT_DIR" && git status --short 2>/dev/null | head -20 || true)
    GIT_RECENT=$(cd "$PROJECT_DIR" && git log --oneline -5 2>/dev/null || true)
fi

ACTIVE_SPECS=$(render_dir_list "$PROJECT_DIR/.claude/memory/specs")
ACTIVE_DECISIONS=$(render_dir_list "$PROJECT_DIR/.claude/memory/decisions")

# 세션 로그 작성
cat > "$LOG_FILE" << EOF
# Session Summary: ${DATE} ${TIME}

## Phase
${CURRENT_PHASE}

## Git Status
\`\`\`
${GIT_STATUS:-"No git repository or no changes"}
\`\`\`

## Recent Commits
\`\`\`
${GIT_RECENT:-"No git repository or no commits"}
\`\`\`

## Active Specs
${ACTIVE_SPECS}

## Active Decisions
${ACTIVE_DECISIONS}

---
*Auto-generated by Crucible session-compact hook*
EOF

echo "Crucible: Session summary saved to ${LOG_FILE}"
